// SPDX-License-Identifier: MIT

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Injure.Analyzers.Shared;

namespace Injure.Analyzers.Generators;

[Generator]
public sealed class StronglyTypedIntGenerator : IIncrementalGenerator {
	// ==========================================================================
	// internal types
	private sealed class TargetInfo(INamedTypeSymbol symbol, string? ns, string backingTypeName, bool isSigned) {
		public INamedTypeSymbol Symbol { get; } = symbol;
		public string? Namespace { get; } = ns;
		public string BackingTypeName { get; } = backingTypeName;
		public bool IsSigned { get; } = isSigned;
	}

	// ==========================================================================
	// IIncrementalGenerator
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		context.RegisterPostInitializationOutput(static (IncrementalGeneratorPostInitializationContext ctx) =>
			ctx.AddSource(AttributeSources.StronglyTypedIntAttributeFilename, SourceText.From(AttributeSources.StronglyTypedIntAttribute, Encoding.UTF8))
		);
		IncrementalValuesProvider<TargetInfo?> targets = context.SyntaxProvider.ForAttributeWithMetadataName(
			AttributeSources.StronglyTypedIntAttributeMetadataName,
			predicate: static (SyntaxNode node, CancellationToken _) => node is StructDeclarationSyntax,
			transform: check
		);
		context.RegisterSourceOutput(targets.Collect(), static (SourceProductionContext ctx, ImmutableArray<TargetInfo?> infos) => {
			HashSet<INamedTypeSymbol> seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
			foreach (TargetInfo? info in infos) {
				if (info is null || !seen.Add(info.Symbol))
					continue;
				ctx.AddSource(getHintName(info), SourceText.From(emit(info), Encoding.UTF8));
			}
		});
	}

	private static string getHintName(TargetInfo info) =>
		(info.Namespace is not null ? info.Namespace + "." + info.Symbol.Name : info.Symbol.Name) + Constants.StronglyTypedIntGeneratedSourceSuffix;

	private static TargetInfo? check(GeneratorAttributeSyntaxContext ctx, CancellationToken ct) {
		INamedTypeSymbol sym = (INamedTypeSymbol)ctx.TargetSymbol;
		if (sym.TypeKind != TypeKind.Struct || !Util.Partial(sym, ct) || !sym.IsReadOnly ||
			sym.ContainingType is not null || sym.TypeParameters.Length != 0 || sym.IsRecord)
			return null;

		AttributeData attr = ctx.Attributes[0];
		if (attr.ConstructorArguments.Length != 1 || attr.ConstructorArguments[0].Value is not INamedTypeSymbol backingType)
			return null;
		if (!Util.TryGetStronglyTypedIntBackingInfo(backingType, out string? backingTypeName, out bool isSigned) || backingTypeName is null)
			return null;
		if (Util.CheckStronglyTypedIntCollision(sym, backingType, out _, out _))
			return null;

		return new TargetInfo(sym, Util.GetNamespace(sym), backingTypeName, isSigned);
	}

	// ==========================================================================
	// source emission
	private static string emit(TargetInfo info) {
		string targetType = info.Symbol.Name;
		string backingType = info.BackingTypeName;
		string one = $"({backingType})1";
		StringBuilder sb = new StringBuilder();

		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using System;");
		if (info.Namespace is not null)
			sb.Append("namespace ").Append(info.Namespace).AppendLine(" {");

		sb.Append('\t').Append(accessibility(info.Symbol)).Append("readonly partial struct ").Append(targetType).Append(" : global::System.IEquatable<").
			Append(targetType).Append(">, global::System.IComparable<").Append(targetType).AppendLine(">,");
		sb.Append("\tglobal::System.IComparable, global::System.ISpanFormattable, global::System.IParsable<").Append(targetType).AppendLine(">,");
		sb.Append("\tglobal::System.ISpanParsable<").Append(targetType).AppendLine("> {");
		sb.Append("\t\tprivate readonly ").Append(backingType).Append(' ').Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic ").Append(backingType).Append(" Value => ").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static readonly ").Append(targetType).AppendLine(" Zero = new(0);");
		sb.Append("\t\tpublic ").Append(targetType).Append("(").Append(backingType).AppendLine(" val) {");
		sb.Append("\t\t\t").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(" = val;");
		sb.AppendLine("\t\t}");

		sb.Append("\t\tpublic static explicit operator ").Append(targetType).Append("(").Append(backingType).AppendLine(" val) => new(val);");
		sb.Append("\t\tpublic static explicit operator checked ").Append(targetType).Append("(").Append(backingType).AppendLine(" val) => new(checked(val));");
		sb.Append("\t\tpublic static explicit operator ").Append(backingType).Append("(").Append(targetType).Append(" val) => val.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static explicit operator checked ").Append(backingType).Append("(").Append(targetType).Append(" val) => checked(val.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");

		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator +(").Append(targetType).Append(" val) => new(+val.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		if (info.IsSigned) {
			sb.Append("\t\tpublic static ").Append(targetType).Append(" operator -(").Append(targetType).Append(" val) => new(-val.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
			sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked -(").Append(targetType).Append(" val) => new(checked(-val.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine("));");
		}

		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator ++(").Append(targetType).Append(" val) => new(val.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" + ").Append(one).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked ++(").Append(targetType).Append(" val) => new(checked(val.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" + ").Append(one).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator --(").Append(targetType).Append(" val) => new(val.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" - ").Append(one).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked --(").Append(targetType).Append(" val) => new(checked(val.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" - ").Append(one).AppendLine("));");

		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator +(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" + right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked +(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(checked(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" + right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator -(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" - right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked -(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(checked(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" - right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator *(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" * right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked *(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(checked(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" * right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator /(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" / right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked /(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(checked(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" / right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator %(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" % right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");

		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator &(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" & right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator |(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" | right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator ^(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" ^ right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator ~(").Append(targetType).Append(" val) => new(~val.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator <<(").Append(targetType).Append(" val, int n) => new(val.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(" << n);");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator >>(").Append(targetType).Append(" val, int n) => new(val.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(" >> n);");

		sb.Append("\t\tpublic static bool operator ==(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" == right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator !=(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" != right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator <(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" < right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator >(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" > right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator <=(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" <= right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator >=(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(Constants.StronglyTypedIntBackingFieldName).Append(" >= right.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");

		sb.Append("\t\tpublic bool Equals(").Append(targetType).Append(" other) => ").Append(Constants.StronglyTypedIntBackingFieldName).Append(" == other.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic override bool Equals(object? obj) => obj is ").Append(targetType).AppendLine(" other && Equals(other);");
		sb.Append("\t\tpublic override int GetHashCode() => ").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(".GetHashCode();");

		sb.Append("\t\tpublic int CompareTo(").Append(targetType).Append(" other) => ").Append(Constants.StronglyTypedIntBackingFieldName).Append(".CompareTo(other.").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic int CompareTo(object? obj) => obj is ").Append(targetType).AppendLine(" other ? CompareTo(other) : 1;");

		sb.Append("\t\tpublic override string ToString() => ").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(".ToString();");
		sb.Append("\t\tpublic string ToString(string? format, IFormatProvider? provider) => ").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(".ToString(format, provider);");
		sb.Append("\t\tpublic bool TryFormat(Span<char> dst, out int written, ReadOnlySpan<char> format, IFormatProvider? provider) => ").Append(Constants.StronglyTypedIntBackingFieldName).AppendLine(".TryFormat(dst, out written, format, provider);");

		sb.Append("\t\tpublic static ").Append(targetType).Append(" Parse(string s, IFormatProvider? provider) => new(").Append(backingType).AppendLine(".Parse(s, provider));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" Parse(ReadOnlySpan<char> span, IFormatProvider? provider) => new(").Append(backingType).AppendLine(".Parse(span, provider));");
		sb.Append("\t\tpublic static bool TryParse(string? s, IFormatProvider? provider, out ").Append(targetType).Append(" result) { bool ok = ").Append(backingType).Append(".TryParse(s, provider, out ").Append(backingType).AppendLine(" v); result = new(v); return ok; }");
		sb.Append("\t\tpublic static bool TryParse(ReadOnlySpan<char> span, IFormatProvider? provider, out ").Append(targetType).Append(" result) { bool ok = ").Append(backingType).Append(".TryParse(span, provider, out ").Append(backingType).AppendLine(" v); result = new(v); return ok; }");

		sb.AppendLine("\t}");
		if (info.Namespace is not null)
			sb.AppendLine("}");
		return sb.ToString();
	}

	private static string accessibility(INamedTypeSymbol sym) => sym.DeclaredAccessibility switch {
		Accessibility.Public => "public ",
		Accessibility.Internal => "internal ",
		_ => ""
	};
}
