// SPDX-License-Identifier: MIT

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Injure.SourceGen;

[Generator]
public sealed class StronglyTypedIntGenerator : IIncrementalGenerator {
	// ==========================================================================
	// internal types
	private sealed class TargetInfo(INamedTypeSymbol symbol, string? ns, string? backingTypeName, bool isSigned, ImmutableArray<Diagnostic> diagnostics) {
		public INamedTypeSymbol Symbol { get; } = symbol;
		public string? Namespace { get; } = ns;
		public string? BackingTypeName { get; } = backingTypeName;
		public bool IsSigned { get; } = isSigned;
		public ImmutableArray<Diagnostic> Diagnostics { get; } = diagnostics;
		public bool ShouldEmit => Diagnostics.IsDefaultOrEmpty || Diagnostics.Length == 0;

		public static TargetInfo Valid(INamedTypeSymbol symbol, string? ns, string? backingTypeName, bool isSigned) =>
			new TargetInfo(symbol, ns, backingTypeName, isSigned, ImmutableArray<Diagnostic>.Empty);
		public static TargetInfo Invalid(INamedTypeSymbol symbol, Diagnostic diagnostic) =>
			new TargetInfo(symbol, null, null, false, ImmutableArray.Create(diagnostic));
	}

	// ==========================================================================
	// constants
	private const string AttributeSource =
@"// <auto-generated/>
#nullable enable
namespace Injure.SourceGen {
	[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
	public sealed class StronglyTypedIntAttribute : global::System.Attribute {
		public global::System.Type BackingType { get; }
		public StronglyTypedIntAttribute(global::System.Type backingType) {
			BackingType = backingType;
		}
	}
}
";
	private const string AttributeMetadataName = "Injure.SourceGen.StronglyTypedIntAttribute";
	private const string BackingFieldName = "__StronglyTypedInt_value";
	private const string GeneratedSourceSuffix = ".StronglyTypedInt.g.cs";

#pragma warning disable RS2008 // enable analyzer release tracking
	private static readonly DiagnosticDescriptor InvalidTarget = new DiagnosticDescriptor(
		id: "IJ0001",
		title: "invalid target for attribute StronglyTypedInt",
		messageFormat: "{0}",
		category: "StronglyTypedInt",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true
	);
	private static readonly DiagnosticDescriptor MustBeReadonly = new DiagnosticDescriptor(
		id: "IJ0002",
		title: "StronglyTypedInt target must be readonly",
		messageFormat: "StronglyTypedInt target struct '{0}' must be a readonly struct",
		category: "StronglyTypedInt",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true
	);
	private static readonly DiagnosticDescriptor UnsupportedBacking = new DiagnosticDescriptor(
		id: "IJ0003",
		title: "unsupported backing type for StronglyTypedInt",
		messageFormat: "backing type '{0}' is not supported (supported: int, uint, long, ulong, Int128, UInt128)",
		category: "StronglyTypedInt",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true
	);
	private static readonly DiagnosticDescriptor MemberCollision = new DiagnosticDescriptor(
		id: "IJ0004",
		title: "existing member collides with reserved member for StronglyTypedInt",
		messageFormat: "{0}",
		category: "StronglyTypedInt",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true
	);

#pragma warning restore RS2008 // enable analyzer release tracking

	// ==========================================================================
	// IIncrementalGenerator
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		context.RegisterPostInitializationOutput(static (IncrementalGeneratorPostInitializationContext ctx) =>
			ctx.AddSource("StronglyTypedIntAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8))
		);
		IncrementalValuesProvider<TargetInfo> targets = context.SyntaxProvider.ForAttributeWithMetadataName(
			AttributeMetadataName,
			predicate: static (SyntaxNode node, CancellationToken _) => node is StructDeclarationSyntax,
			transform: check
		);
		context.RegisterSourceOutput(targets.Collect(), static (SourceProductionContext ctx, ImmutableArray<TargetInfo> infos) => {
			HashSet<INamedTypeSymbol> seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
			foreach (TargetInfo info in infos) {
				foreach (Diagnostic diag in info.Diagnostics)
					ctx.ReportDiagnostic(diag);
				if (!info.ShouldEmit || !seen.Add(info.Symbol))
					continue;
				ctx.AddSource(getHintName(info), SourceText.From(gen(info), Encoding.UTF8));
			}
		});
	}

	private static string getHintName(TargetInfo info) =>
		(info.Namespace is not null ? info.Namespace + "." + info.Symbol.Name : info.Symbol.Name) + GeneratedSourceSuffix;

	private static TargetInfo check(GeneratorAttributeSyntaxContext ctx, CancellationToken ct) {
		INamedTypeSymbol sym = (INamedTypeSymbol)ctx.TargetSymbol;
		Location loc = ctx.Attributes[0].ApplicationSyntaxReference?.GetSyntax(ct).GetLocation() ?? ctx.TargetNode.GetLocation();
		if (sym.TypeKind != TypeKind.Struct)
			return TargetInfo.Invalid(sym, Diagnostic.Create(InvalidTarget, loc, "Target must be a struct."));
		if (!partial(sym, ct))
			return TargetInfo.Invalid(sym, Diagnostic.Create(InvalidTarget, loc, "Target must be declared 'partial'."));
		if (!sym.IsReadOnly)
			return TargetInfo.Invalid(sym, Diagnostic.Create(MustBeReadonly, loc, sym.Name));
		if (sym.ContainingType is not null)
			return TargetInfo.Invalid(sym, Diagnostic.Create(InvalidTarget, loc, "Nested structs are not supported."));
		if (sym.TypeParameters.Length != 0)
			return TargetInfo.Invalid(sym, Diagnostic.Create(InvalidTarget, loc, "Generic structs are not supported."));
		if (sym.IsRecord)
			return TargetInfo.Invalid(sym, Diagnostic.Create(InvalidTarget, loc, "'record struct' is not supported."));

		AttributeData attr = ctx.Attributes[0];
		if (attr.ConstructorArguments.Length != 1)
			return TargetInfo.Invalid(sym, Diagnostic.Create(InvalidTarget, loc, "Attribute must have exactly one typeof(...) argument."));
		if (attr.ConstructorArguments[0].Value is not INamedTypeSymbol backingType)
			return TargetInfo.Invalid(sym, Diagnostic.Create(InvalidTarget, loc, "Attribute argument must be a concrete type."));
		if (!tryGetBackingInfo(backingType, out string? backingTypeName, out bool isSigned))
			return TargetInfo.Invalid(sym, Diagnostic.Create(UnsupportedBacking, loc, backingType.ToDisplayString()));
		if (checkCollision(sym, backingType, out Location collisionLoc, out string? collisionMsg))
			return TargetInfo.Invalid(sym, Diagnostic.Create(MemberCollision, collisionLoc, collisionMsg));
		string? ns = !sym.ContainingNamespace.IsGlobalNamespace ? sym.ContainingNamespace.ToDisplayString() : null;
		return TargetInfo.Valid(sym, ns, backingTypeName, isSigned);
	}

	private static bool partial(INamedTypeSymbol sym, CancellationToken ct) {
		foreach (SyntaxReference sr in sym.DeclaringSyntaxReferences)
			if (sr.GetSyntax(ct) is StructDeclarationSyntax s && s.Modifiers.Any(SyntaxKind.PartialKeyword))
				return true;
		return false;
	}

	private static bool tryGetBackingInfo(INamedTypeSymbol sym, /* [NotNullWhen(true)] */ out string? name, out bool signed) {
		switch (sym.SpecialType) {
		case SpecialType.System_Int32:
			name = "int";
			signed = true;
			return true;
		case SpecialType.System_UInt32:
			name = "uint";
			signed = false;
			return true;
		case SpecialType.System_Int64:
			name = "long";
			signed = true;
			return true;
		case SpecialType.System_UInt64:
			name = "ulong";
			signed = false;
			return true;
		}
		if (sym.ContainingNamespace.ToDisplayString() == "System") {
			switch (sym.Name) {
			case "Int128":
				name = "global::System.Int128";
				signed = true;
				return true;
			case "UInt128":
				name = "global::System.UInt128";
				signed = false;
				return true;
			}
		}

		name = null;
		signed = false;
		return false;
	}

	private static bool checkCollision(INamedTypeSymbol sym, INamedTypeSymbol backingType, out Location loc, /* [NotNullWhen(true)] */ out string? msg) {
		ImmutableArray<ISymbol> members = sym.GetMembers(BackingFieldName);
		if (members.Length != 0) {
			loc = getLocation(members[0], sym);
			msg = $"Type '{sym.Name}' already contains a member named '{BackingFieldName}', which is reserved by StronglyTypedInt.";
			return true;
		}
		foreach (IMethodSymbol ctor in sym.InstanceConstructors) {
			if (ctor.IsImplicitlyDeclared || ctor.Parameters.Length != 1 ||
				SymbolEqualityComparer.Default.Equals(ctor.Parameters[0].Type, backingType))
				continue;
			loc = getLocation(ctor, sym);
			msg = $"Type '{sym.Name}' already contains a constructor with signature '({backingType.ToDisplayString()})', which conflicts with generated code.";
			return true;
		}
		loc = sym.Locations.FirstOrDefault(static (Location l) => l.IsInSource) ?? Location.None;
		msg = null;
		return false;
	}

	private static Location getLocation(ISymbol sym, INamedTypeSymbol fallback) {
		return sym.Locations.FirstOrDefault(static (Location l) => l.IsInSource) ??
			fallback.Locations.FirstOrDefault(static (Location l) => l.IsInSource) ??
			Location.None;
	}

	// ==========================================================================
	// the actual generation
	private static string gen(TargetInfo info) {
		string targetType = info.Symbol.Name;
		string? backingType = info.BackingTypeName;
		string one = $"({backingType})1";
		StringBuilder sb = new StringBuilder();

		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");

		// using System;
		// namespace Namespace {
		sb.AppendLine("using System;");
		if (info.Namespace is not null)
			sb.Append("namespace ").Append(info.Namespace).AppendLine(" {");

		// readonly partial struct TargetType : global::System.IEquatable<TargetType>, global::System.IComparable<TargetType>,
		// 	global::System.IComparable, global::System.ISpanFormattable, global::System.IParsable<TargetType>,
		// 	global::System.ISpanParsable<TargetType> {
		// 	private readonly BackingType BackingFieldName;
		// 	public BackingType Value => BackingFieldName;
		// 	public static readonly TargetType Zero = new(0);
		// 	public TargetType(BackingType val) {
		// 		BackingFieldName = val;
		// 	}
		sb.Append("\treadonly partial struct ").Append(targetType).Append(" : global::System.IEquatable<").
			Append(targetType).Append(">, global::System.IComparable<").Append(targetType).AppendLine(">,");
		sb.Append("\tglobal::System.IComparable, global::System.ISpanFormattable, global::System.IParsable<").
			Append(targetType).AppendLine(">,");
		sb.Append("\tglobal::System.ISpanParsable<").Append(targetType).AppendLine("> {");
		sb.Append("\t\tprivate readonly ").Append(backingType).Append(' ').Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic ").Append(backingType).Append(" Value => ").Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static readonly ").Append(targetType).AppendLine(" Zero = new(0);");
		sb.Append("\t\tpublic ").Append(targetType).Append("(").Append(backingType).AppendLine(" val) {");
		sb.Append("\t\t\t").Append(BackingFieldName).AppendLine(" = val;");
		sb.AppendLine("\t\t}");

		// public static explicit operator TargetType(BackingType val) => new(val);
		// public static explicit operator checked TargetType(BackingType val) => new(checked(val));
		// public static explicit operator BackingType(TargetType val) => val.BackingFieldName;
		// public static explicit operator checked BackingType(TargetType val) => checked(val.BackingFieldName);
		sb.Append("\t\tpublic static explicit operator ").Append(targetType).Append("(").Append(backingType).AppendLine(" val) => new(val);");
		sb.Append("\t\tpublic static explicit operator checked ").Append(targetType).Append("(").Append(backingType).AppendLine(" val) => new(checked(val));");
		sb.Append("\t\tpublic static explicit operator ").Append(backingType).Append("(").Append(targetType).Append(" val) => val.").Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static explicit operator checked ").Append(backingType).Append("(").Append(targetType).Append(" val) => checked(val.").Append(BackingFieldName).AppendLine(");");

		// public static TargetType operator +(TargetType val) => new(+val.BackingFieldName);
		// public static TargetType operator -(TargetType val) => new(-val.BackingFieldName);
		// public static TargetType operator checked -(TargetType val) => new(checked(-val.BackingFieldName));
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator +(").Append(targetType).Append(" val) => new(+val.").Append(BackingFieldName).AppendLine(");");
		if (info.IsSigned) {
			sb.Append("\t\tpublic static ").Append(targetType).Append(" operator -(").Append(targetType).Append(" val) => new(-val.").Append(BackingFieldName).AppendLine(");");
			sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked -(").Append(targetType).Append(" val) => new(checked(-val.").Append(BackingFieldName).AppendLine("));");
		}

		// public static TargetType operator ++(TargetType val) => new(val.BackingFieldName + (BackingType)1);
		// public static TargetType operator checked ++(TargetType val) => new(checked(val.BackingFieldName + (BackingType)1));
		// public static TargetType operator --(TargetType val) => new(val.BackingFieldName - (BackingType)1);
		// public static TargetType operator checked --(TargetType val) => new(checked(val.BackingFieldName - (BackingType)1));
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator ++(").Append(targetType).Append(" val) => new(val.").Append(BackingFieldName).Append(" + ").Append(one).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked ++(").Append(targetType).Append(" val) => new(checked(val.").Append(BackingFieldName).Append(" + ").Append(one).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator --(").Append(targetType).Append(" val) => new(val.").Append(BackingFieldName).Append(" - ").Append(one).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked --(").Append(targetType).Append(" val) => new(checked(val.").Append(BackingFieldName).Append(" - ").Append(one).AppendLine("));");

		// public static TargetType operator +(TargetType left, TargetType right) => new(left.BackingFieldName + right.BackingFieldName);
		// public static TargetType operator checked +(TargetType left, TargetType right) => new(checked(left.BackingFieldName + right.BackingFieldName));
		// public static TargetType operator -(TargetType left, TargetType right) => new(left.BackingFieldName - right.BackingFieldName);
		// public static TargetType operator checked -(TargetType left, TargetType right) => new(checked(left.BackingFieldName - right.BackingFieldName));
		// public static TargetType operator *(TargetType left, TargetType right) => new(left.BackingFieldName * right.BackingFieldName);
		// public static TargetType operator checked *(TargetType left, TargetType right) => new(checked(left.BackingFieldName * right.BackingFieldName));
		// public static TargetType operator /(TargetType left, TargetType right) => new(left.BackingFieldName / right.BackingFieldName);
		// public static TargetType operator checked /(TargetType left, TargetType right) => new(checked(left.BackingFieldName / right.BackingFieldName));
		// public static TargetType operator %(TargetType left, TargetType right) => new(left.BackingFieldName % right.BackingFieldName);
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator +(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(BackingFieldName).Append(" + right.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked +(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(checked(left.").Append(BackingFieldName).Append(" + right.").Append(BackingFieldName).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator -(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(BackingFieldName).Append(" - right.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked -(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(checked(left.").Append(BackingFieldName).Append(" - right.").Append(BackingFieldName).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator *(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(BackingFieldName).Append(" * right.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked *(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(checked(left.").Append(BackingFieldName).Append(" * right.").Append(BackingFieldName).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator /(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(BackingFieldName).Append(" / right.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator checked /(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(checked(left.").Append(BackingFieldName).Append(" / right.").Append(BackingFieldName).AppendLine("));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator %(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(BackingFieldName).Append(" % right.").Append(BackingFieldName).AppendLine(");");

		// public static TargetType operator &(TargetType left, TargetType right) => new(left.BackingFieldName & right.BackingFieldName);
		// public static TargetType operator |(TargetType left, TargetType right) => new(left.BackingFieldName | right.BackingFieldName);
		// public static TargetType operator ^(TargetType left, TargetType right) => new(left.BackingFieldName ^ right.BackingFieldName);
		// public static TargetType operator ~(TargetType val) => new(~val.BackingFieldName);
		// public static TargetType operator <<(TargetType val, int n) => new(val.BackingFieldName << n);
		// public static TargetType operator >>(TargetType val, int n) => new(val.BackingFieldName >> n);
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator &(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(BackingFieldName).Append(" & right.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator |(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(BackingFieldName).Append(" | right.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator ^(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => new(left.").Append(BackingFieldName).Append(" ^ right.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator ~(").Append(targetType).Append(" val) => new(~val.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator <<(").Append(targetType).Append(" val, int n) => new(val.").Append(BackingFieldName).AppendLine(" << n);");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" operator >>(").Append(targetType).Append(" val, int n) => new(val.").Append(BackingFieldName).AppendLine(" >> n);");

		// public static bool operator ==(TargetType left, TargetType right) => left.BackingFieldName == right.BackingFieldName;
		// public static bool operator !=(TargetType left, TargetType right) => left.BackingFieldName != right.BackingFieldName;
		// public static bool operator <(TargetType left, TargetType right) => left.BackingFieldName < right.BackingFieldName;
		// public static bool operator >(TargetType left, TargetType right) => left.BackingFieldName > right.BackingFieldName;
		// public static bool operator <=(TargetType left, TargetType right) => left.BackingFieldName <= right.BackingFieldName;
		// public static bool operator >=(TargetType left, TargetType right) => left.BackingFieldName >= right.BackingFieldName;
		sb.Append("\t\tpublic static bool operator ==(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(BackingFieldName).Append(" == right.").Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator !=(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(BackingFieldName).Append(" != right.").Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator <(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(BackingFieldName).Append(" < right.").Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator >(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(BackingFieldName).Append(" > right.").Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator <=(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(BackingFieldName).Append(" <= right.").Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic static bool operator >=(").Append(targetType).Append(" left, ").Append(targetType).Append(" right) => left.").Append(BackingFieldName).Append(" >= right.").Append(BackingFieldName).AppendLine(";");

		// public bool Equals(TargetType other) => BackingFieldName == other.BackingFieldName;
		// public override bool Equals(object? obj) => obj is TargetType other && Equals(other);
		// public override int GetHashCode() => BackingFieldName.GetHashCode();
		sb.Append("\t\tpublic bool Equals(").Append(targetType).Append(" other) => ").Append(BackingFieldName).Append(" == other.").Append(BackingFieldName).AppendLine(";");
		sb.Append("\t\tpublic override bool Equals(object? obj) => obj is ").Append(targetType).AppendLine(" other && Equals(other);");
		sb.Append("\t\tpublic override int GetHashCode() => ").Append(BackingFieldName).AppendLine(".GetHashCode();");

		// public int CompareTo(TargetType other) => BackingFieldName.CompareTo(other.BackingFieldName);
		// public int CompareTo(object? obj) => obj is TargetType other ? CompareTo(other) : 1;
		sb.Append("\t\tpublic int CompareTo(").Append(targetType).Append(" other) => ").Append(BackingFieldName).Append(".CompareTo(other.").Append(BackingFieldName).AppendLine(");");
		sb.Append("\t\tpublic int CompareTo(object? obj) => obj is ").Append(targetType).AppendLine(" other ? CompareTo(other) : 1;");

		// public override string ToString() => BackingFieldName.ToString();
		// public string ToString(string? format, IFormatProvider? provider) => BackingFieldName.ToString(format, provider);
		sb.Append("\t\tpublic override string ToString() => ").Append(BackingFieldName).AppendLine(".ToString();");
		sb.Append("\t\tpublic string ToString(string? format, IFormatProvider? provider) => ").Append(BackingFieldName).AppendLine(".ToString(format, provider);");

		// public bool TryFormat(Span<char> dst, out int written, ReadOnlySpan<char> format, IFormatProvider? provider) => BackingFieldName.TryFormat(dst, out written, format, provider);
		sb.Append("\t\tpublic bool TryFormat(Span<char> dst, out int written, ReadOnlySpan<char> format, IFormatProvider? provider) => ").Append(BackingFieldName).AppendLine(".TryFormat(dst, out written, format, provider);");

		// public static TargetType Parse(string s, IFormatProvider? provider) => new(BackingType.Parse(s, provider));
		// public static TargetType Parse(ReadOnlySpan<char> span, IFormatProvider? provider) => new(BackingType.Parse(span, provider));
		sb.Append("\t\tpublic static ").Append(targetType).Append(" Parse(string s, IFormatProvider? provider) => new(").Append(backingType).AppendLine(".Parse(s, provider));");
		sb.Append("\t\tpublic static ").Append(targetType).Append(" Parse(ReadOnlySpan<char> span, IFormatProvider? provider) => new(").Append(backingType).AppendLine(".Parse(span, provider));");

		// public static bool TryParse(string? s, IFormatProvider? provider, out TargetType result) { bool ok = BackingType.TryParse(s, provider, out BackingType v); result = new(v); return ok; }
		// public static bool TryParse(ReadOnlySpan<char> span, IFormatProvider? provider, out TargetType result) { bool ok = BackingType.TryParse(span, provider, out BackingType v); result = new(v); return ok; }
		sb.Append("\t\tpublic static bool TryParse(string? s, IFormatProvider? provider, out ").Append(targetType).Append(" result) { bool ok = ").Append(backingType).Append(".TryParse(s, provider, out ").Append(backingType).AppendLine(" v); result = new(v); return ok; }");
		sb.Append("\t\tpublic static bool TryParse(ReadOnlySpan<char> span, IFormatProvider? provider, out ").Append(targetType).Append(" result) { bool ok = ").Append(backingType).Append(".TryParse(span, provider, out ").Append(backingType).AppendLine(" v); result = new(v); return ok; }");

		// close struct
		sb.AppendLine("\t}");

		// close namespace
		if (info.Namespace is not null)
			sb.AppendLine("}");

		return sb.ToString();
	}
}
